name: Test Workflow
on: push
jobs:
 checkout:
  runs-on: ubuntu-latest
  steps:
   - run: ls -al
   - uses: actions/checkout@v3
     with:
      path: our-source
   - run: ls -al
   - run: ls -al our-source

 crossfit-whale-member-be-deploy:
   runs-on: ubuntu-latest  # 실행 환경 지정
   # 실행 단계 지정
   steps:
     - name: execute remote ssh
       uses: appleboy/ssh-action@v1.0.3
       with:
         host: ${{ secrets.REMOTE_SSH_HOST }}
         username: ${{ secrets.REMOTE_SSH_USERNAME }}
         key: ${{ secrets.REMOTE_SSH_KEY }}
         passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
         port: ${{ secrets.REMOTE_SSH_PORT }}
         script: | 
           whoami
